parameters:
    sansis_core_devel.service.reverse: SanSIS\Core\DevelBundle\Service\ReverseService
    sansis_core_devel.service.generate: SanSIS\Core\DevelBundle\Service\GenerateService

services:
    sansis_core_devel.service_reverse:
        class: %sansis_core_devel.service.reverse%
        arguments: ["@doctrine.orm.entity_manager"]
        
    sansis_core_devel.service_generate:
        class: %sansis_core_devel.service.generate%
        arguments: ["@doctrine.orm.entity_manager"]
